#!/bin/bash

# selection_sort () { }

A=(32 14 55 21 27 75 10)
n=${#A[@]}

# for i in {0..n-1};
for (( i=0; i<n-1; i++ ));
do
    m=$i
    for (( j=i+1; j<n; j++ ));
    do
        if [[ ${A[j]} -lt ${A[m]} ]]; then
            m=$j
        fi
    done

    # swap A[i], A[m]
    temp=${A[i]}
    A[i]=${A[m]}
    A[m]=$temp

done

echo ${A[@]}
